---
name: Update Google Fonts
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch: null
env:
  PNPM_VERSION: 7.24.3
  NODE_LTS_VERSION: 18
  # required for gh cli
  GH_TOKEN: ${{ github.token }}

jobs:
  update-fonts:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          check-latest: true
      - uses: actions/checkout@v3
        with:
          fetch-depth: 25
      - run: npm i -g pnpm@${{ env.PNPM_VERSION }}
      - id: get-store-path
        run: echo STORE_PATH=$(pnpm store path) >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        timeout-minutes: 5
        id: cache-pnpm-store
        with:
          path: ${{ steps.get-store-path.outputs.STORE_PATH }}
          key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-
            pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install
      - run: pnpm run update-google-fonts
      - name: Commit and push changes
        run: |
          git fetch origin canary
          git fetch origin automated/update-google-fonts
          git config user.name "vercel-release-bot"
          git config user.email "infra+release@vercel.com"
          git checkout automated/update-google-fonts 2>/dev/null || git checkout -b automated/update-google-fonts
          git add -A
          git commit -m "Update Google Fonts"
          git push --set-upstream origin automated/update-google-fonts
      - name: Open pull request
        run: |
          gh pr create --fill --body "Update Google Fonts" --head update-google-fonts --base canary
